/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppQuotesIndexRouteImport } from './routes/_app/quotes/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppQuotesNewRouteImport } from './routes/_app/quotes/new'
import { Route as AppQuotesIdRouteImport } from './routes/_app/quotes/$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'
import { Route as AppQuotesIdIndexRouteImport } from './routes/_app/quotes/$id.index'
import { Route as AppInvoicesIdIndexRouteImport } from './routes/_app/invoices/$id.index'
import { Route as AppQuotesIdEditRouteImport } from './routes/_app/quotes/$id.edit'
import { Route as AppInvoicesIdEditRouteImport } from './routes/_app/invoices/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesNewRoute = AppQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIdRoute = AppQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIdIndexRoute = AppQuotesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuotesIdRoute,
} as any)
const AppInvoicesIdIndexRoute = AppInvoicesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesIdRoute,
} as any)
const AppQuotesIdEditRoute = AppQuotesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppQuotesIdRoute,
} as any)
const AppInvoicesIdEditRoute = AppInvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppInvoicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/settings': typeof AppSettingsRoute
  '/invoices/$id': typeof AppInvoicesIdRouteWithChildren
  '/quotes/$id': typeof AppQuotesIdRouteWithChildren
  '/quotes/new': typeof AppQuotesNewRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/quotes/$id/edit': typeof AppQuotesIdEditRoute
  '/invoices/$id/': typeof AppInvoicesIdIndexRoute
  '/quotes/$id/': typeof AppQuotesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/settings': typeof AppSettingsRoute
  '/quotes/new': typeof AppQuotesNewRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/quotes/$id/edit': typeof AppQuotesIdEditRoute
  '/invoices/$id': typeof AppInvoicesIdIndexRoute
  '/quotes/$id': typeof AppQuotesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRouteWithChildren
  '/_app/quotes/$id': typeof AppQuotesIdRouteWithChildren
  '/_app/quotes/new': typeof AppQuotesNewRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/invoices/$id/edit': typeof AppInvoicesIdEditRoute
  '/_app/quotes/$id/edit': typeof AppQuotesIdEditRoute
  '/_app/invoices/$id/': typeof AppInvoicesIdIndexRoute
  '/_app/quotes/$id/': typeof AppQuotesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/follow-ups'
    | '/settings'
    | '/invoices/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/invoices/'
    | '/quotes/'
    | '/invoices/$id/edit'
    | '/quotes/$id/edit'
    | '/invoices/$id/'
    | '/quotes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/follow-ups'
    | '/settings'
    | '/quotes/new'
    | '/invoices'
    | '/quotes'
    | '/invoices/$id/edit'
    | '/quotes/$id/edit'
    | '/invoices/$id'
    | '/quotes/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/follow-ups'
    | '/_app/settings'
    | '/_app/invoices/$id'
    | '/_app/quotes/$id'
    | '/_app/quotes/new'
    | '/_app/invoices/'
    | '/_app/quotes/'
    | '/_app/invoices/$id/edit'
    | '/_app/quotes/$id/edit'
    | '/_app/invoices/$id/'
    | '/_app/quotes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/new': {
      id: '/_app/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AppQuotesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$id': {
      id: '/_app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AppQuotesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$id/': {
      id: '/_app/quotes/$id/'
      path: '/'
      fullPath: '/quotes/$id/'
      preLoaderRoute: typeof AppQuotesIdIndexRouteImport
      parentRoute: typeof AppQuotesIdRoute
    }
    '/_app/invoices/$id/': {
      id: '/_app/invoices/$id/'
      path: '/'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof AppInvoicesIdIndexRouteImport
      parentRoute: typeof AppInvoicesIdRoute
    }
    '/_app/quotes/$id/edit': {
      id: '/_app/quotes/$id/edit'
      path: '/edit'
      fullPath: '/quotes/$id/edit'
      preLoaderRoute: typeof AppQuotesIdEditRouteImport
      parentRoute: typeof AppQuotesIdRoute
    }
    '/_app/invoices/$id/edit': {
      id: '/_app/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AppInvoicesIdEditRouteImport
      parentRoute: typeof AppInvoicesIdRoute
    }
  }
}

interface AppInvoicesIdRouteChildren {
  AppInvoicesIdEditRoute: typeof AppInvoicesIdEditRoute
  AppInvoicesIdIndexRoute: typeof AppInvoicesIdIndexRoute
}

const AppInvoicesIdRouteChildren: AppInvoicesIdRouteChildren = {
  AppInvoicesIdEditRoute: AppInvoicesIdEditRoute,
  AppInvoicesIdIndexRoute: AppInvoicesIdIndexRoute,
}

const AppInvoicesIdRouteWithChildren = AppInvoicesIdRoute._addFileChildren(
  AppInvoicesIdRouteChildren,
)

interface AppQuotesIdRouteChildren {
  AppQuotesIdEditRoute: typeof AppQuotesIdEditRoute
  AppQuotesIdIndexRoute: typeof AppQuotesIdIndexRoute
}

const AppQuotesIdRouteChildren: AppQuotesIdRouteChildren = {
  AppQuotesIdEditRoute: AppQuotesIdEditRoute,
  AppQuotesIdIndexRoute: AppQuotesIdIndexRoute,
}

const AppQuotesIdRouteWithChildren = AppQuotesIdRoute._addFileChildren(
  AppQuotesIdRouteChildren,
)

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRouteWithChildren
  AppQuotesIdRoute: typeof AppQuotesIdRouteWithChildren
  AppQuotesNewRoute: typeof AppQuotesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppInvoicesIdRoute: AppInvoicesIdRouteWithChildren,
  AppQuotesIdRoute: AppQuotesIdRouteWithChildren,
  AppQuotesNewRoute: AppQuotesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
